// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using techlingo.projeto.Repository.Context;

#nullable disable

namespace techlingo.projeto.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230513142846_CRIACAO")]
    partial class CRIACAO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("techlingo.projeto.Models.tl_alunoModel", b =>
                {
                    b.Property<int>("id_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALUNO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aluno"));

                    b.Property<string>("ds_email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<DateTime>("dt_nascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("nm_aluno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_ALUNO");

                    b.Property<string>("nr_cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CPF");

                    b.Property<int>("planoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_PLANO");

                    b.HasKey("id_aluno");

                    b.HasIndex("planoId");

                    b.ToTable("TL_ALUNO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_aluno_cursoModel", b =>
                {
                    b.Property<int>("alunoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALUNO");

                    b.Property<int>("cursoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURSO");

                    b.Property<int>("nr_nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NOTA");

                    b.Property<string>("st_status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_STATUS");

                    b.HasKey("alunoId", "cursoId");

                    b.HasIndex("cursoId");

                    b.ToTable("TL_ALUNO_CURSO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_cursoModel", b =>
                {
                    b.Property<int>("id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_curso"));

                    b.Property<string>("ds_duracao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_DURACAO");

                    b.Property<string>("nm_curso")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_CURSO");

                    b.HasKey("id_curso");

                    b.ToTable("TL_CURSO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_planoModel", b =>
                {
                    b.Property<int>("id_plano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plano"));

                    b.Property<string>("nm_plano")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_PLANO");

                    b.Property<decimal>("vl_plano")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VL_PLANO");

                    b.HasKey("id_plano");

                    b.ToTable("TL_PLANO");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_alunoModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.tl_planoModel", "plano")
                        .WithMany()
                        .HasForeignKey("planoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plano");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_aluno_cursoModel", b =>
                {
                    b.HasOne("techlingo.projeto.Models.tl_alunoModel", "tl_alunoModel")
                        .WithMany("aluno_cursos")
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techlingo.projeto.Models.tl_cursoModel", "tl_cursoModel")
                        .WithMany("aluno_cursos")
                        .HasForeignKey("cursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tl_alunoModel");

                    b.Navigation("tl_cursoModel");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_alunoModel", b =>
                {
                    b.Navigation("aluno_cursos");
                });

            modelBuilder.Entity("techlingo.projeto.Models.tl_cursoModel", b =>
                {
                    b.Navigation("aluno_cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
